# Generated by Django 4.1 on 2022-10-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='brand_id',
            new_name='brand',
        ),
    ]
